server:
  port: 9012
spring:
  application:
    name: jaygame-web
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    jaygame-base: #activity
      path: /base/**      #URL rule
      serviceId: jaygame-base  #Euraka register center service id